<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Student REgistration Form </title>
</head>
<body>

 <form:form action="processForm" modelAttribute="student">
 
 First Name: <form:input path="firstName"/>
<br>
<br>
 Last Name: <form:input path="lastName"/>
 
 <br>
<%--  <form:select path="country"> --%>
 
<%--  <form:option value="Brazil" label="Brazil"></form:option> --%>
<%--  <form:option value="Ireland" label="Ireland"></form:option> --%>
<%--  <form:option value="India" label="India"></form:option> --%>
<%--  <form:option value="Bangladesh" label="bangldesh"></form:option> --%>
<%--  <form:option value="US" label="US"></form:option> --%>
<!--  <br> -->
 Autogenerated
 
 <form:select path="country">
 
 <form:options items="${newcountryOptions}"/>
 </form:select>
 
 <br>
 
 Favorite Language

Java <form:radiobutton path="favoriteLanguage" value="Java"/> <br>

Java <form:radiobutton path="favoriteLanguage" value="Kotlin"/> <br>

Java <form:radiobutton path="favoriteLanguage" value="PHP"/> <br>

Java <form:radiobutton path="favoriteLanguage" value="Python"/> <br> 

<br>
Which operating systems you have experice in 

linux <form:checkbox path="operatingSystem" value="linux"/> <br>
Windows<form:checkbox path="operatingSystem" value="Windows"/> <br>
MAc <form:checkbox path="operatingSystem" value="mac"/> <br>

 
 
 
 
 
 <br>
 <form:button>Submit</form:button>
 
 </form:form>
</body>
</html>